# Generated by Django 4.1.2 on 2022-10-30 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('blog_id', models.CharField(max_length=5)),
                ('caption', models.CharField(max_length=1500, verbose_name='متن')),
                ('score', models.IntegerField(db_index=True, default=0, verbose_name='جمع امتیازات')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_blog', to='api.article', verbose_name='مطلب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_user', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز دهنده')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازات',
            },
        ),
    ]
